development:
  bucket_name: rentareto
  access_key_id: AKIAIETPPQ55S3QZGFQA
  secret_access_key: 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

test:
  bucket_name: rentareto
  access_key_id: AKIAIETPPQ55S3QZGFQA
  secret_access_key: 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

production:
  bucket_name: rentareto
  access_key_id: AKIAIETPPQ55S3QZGFQA
  secret_access_key: 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
